Chart contains template spec with security context (#77)
Having securityContext within deployment template object causes this error running on k3s version v1.31.12+k3s1:

```
Release "kubeftpd" does not exist. Installing it now.
Error: failed to create typed patch object (ftp/kubeftpd-controller-manager; apps/v1, Kind=Deployment): .spec.template.spec.securityContext.allowPrivilegeEscalation: field not declared in schema
```